apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agent-office
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/enterprisewebservice/agent-office.git
    targetRevision: main
    path: manifests
    directory:
      recurse: true
      exclude: 'gitops/*'
  destination:
    server: https://kubernetes.default.svc
    namespace: agent-office
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
