/*
 * useMemoryModuleStrategy
 *
 * Strategy for the "Memory Modules" tab.
 *   - Lists MemoryModule CRs in the AW's namespace
 *   - Reads current spec.memory.modules from the AW
 *   - No role picker — MemoryModuleRef is just {name}
 *   - No gateway-grey-out — MemoryModules are namespace-scoped, not
 *     gateway-scoped (the operator composes their content into the
 *     agent's rendered AGENTS.md / USER.md / TOOLS.md regardless of
 *     where the agent runs)
 *   - Save fires the same scaffolder template as KB strategy
 */
import { useEffect, useState } from 'react';
import yaml from 'js-yaml';
import { BindingStrategy, BindingItem } from '../BindingPanel';
import { useProxiedK8s } from './useProxiedK8s';
import { useScaffolderPR } from './useScaffolderPR';

interface AwSpec {
  spec: {
    memory?: { modules?: { name: string }[]; overrides?: Record<string, string> };
  };
}

interface GitopsSource {
  filePath: string;
}

interface MmList {
  items: Array<{
    name: string;
    displayName?: string;
    kind: string;
    filename: string;
    version?: string;
  }>;
}

export const useMemoryModuleStrategy = ({
  awName,
  awNamespace,
}: {
  awName: string;
  awNamespace: string;
}): BindingStrategy => {
  const { get } = useProxiedK8s();
  const openPR = useScaffolderPR();

  const [available, setAvailable] = useState<BindingItem[]>([]);
  const [attached, setAttached] = useState<BindingItem[]>([]);
  const [aw, setAw] = useState<AwSpec | null>(null);
  const [gitops, setGitops] = useState<GitopsSource | null>(null);
  const [saving, setSaving] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | undefined>();

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const [mmList, awSpec, gitopsSrc] = await Promise.all([
          get<MmList>(`/namespaces/${awNamespace}/memorymodules`),
          get<AwSpec>(`/namespaces/${awNamespace}/agentworkstations/${awName}`),
          get<GitopsSource>(
            `/namespaces/${awNamespace}/agentworkstations/${awName}/gitops-source`,
          ),
        ]);
        if (cancelled) return;
        setAvailable(
          mmList.items.map(m => ({
            name: m.name,
            displayName: m.displayName ?? m.name,
            description: `${m.kind} → ${m.filename}${m.version ? ` (v${m.version})` : ''}`,
          })),
        );
        const refs = awSpec.spec.memory?.modules ?? [];
        setAttached(
          refs.map(ref => {
            const meta = mmList.items.find(m => m.name === ref.name);
            return {
              name: ref.name,
              displayName: meta?.displayName ?? ref.name,
              description: meta
                ? `${meta.kind} → ${meta.filename}${meta.version ? ` (v${meta.version})` : ''}`
                : undefined,
            };
          }),
        );
        setAw(awSpec);
        setGitops(gitopsSrc);
        setErrorMessage(undefined);
      } catch (err) {
        if (!cancelled) {
          setErrorMessage(
            (err as Error).message +
              ' — most commonly: this entity has no matching AgentWorkstation CR. Set the `agentoffice.ai/agentworkstation-name` annotation on the entity to point at the AW you want bindings managed for.',
          );
        }
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [awName, awNamespace, get]);

  const onSave = async (next: BindingItem[]) => {
    if (!aw || !gitops) {
      throw new Error('AW spec or gitops source not loaded yet');
    }
    setSaving(true);
    try {
      const newRefs = next.map(i => ({ name: i.name }));
      const updatedSpec = {
        ...aw.spec,
        memory: {
          ...(aw.spec.memory ?? {}),
          modules: newRefs.length > 0 ? newRefs : undefined,
        },
      };
      const newContent = yaml.dump({
        apiVersion: 'agentoffice.ai/v1alpha1',
        kind: 'AgentWorkstation',
        metadata: { name: awName, namespace: awNamespace },
        spec: updatedSpec,
      });

      await openPR({
        awName,
        awNamespace,
        bindingType: 'memory',
        targetPath: gitops.filePath,
        newContent,
        branchName: `aw-binder/${awName}-memory-${Date.now()}`,
        title: `${awName}: update memory-module attachments (${newRefs.length})`,
        body: [
          `Updates \`spec.memory.modules\` on AgentWorkstation \`${awName}\`.`,
          '',
          '## New attachments',
          ...newRefs.map(r => `- \`${r.name}\``),
          '',
          'Generated by the agentworkstation-binders Backstage plugin.',
        ].join('\n'),
      });
      setSaving(false);
    } catch (err) {
      setSaving(false);
      setErrorMessage((err as Error).message);
      throw err;
    }
  };

  return {
    resourceLabel: 'Memory Modules',
    available,
    attached,
    onSave,
    saving,
    errorMessage,
  };
};
