apiVersion: v1
kind: Service
metadata:
  name: __SVC__
  namespace: agent-office
  labels:
    app.kubernetes.io/name: __SVC__
    app.kubernetes.io/part-of: supply-chain-services
spec:
  selector:
    app.kubernetes.io/name: __SVC__
  ports:
    - name: http
      port: 8080
      targetPort: 8080
