apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-demo
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/enterprisewebservice/agent-office.git
    targetRevision: main
    path: cluster/api-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: api-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 10
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 3m
