apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agent-office-help-desk
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/enterprisewebservice/agent-office.git
    targetRevision: main
    path: cluster/help-desk
  destination:
    server: https://kubernetes.default.svc
    namespace: agent-office
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
