apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agent-office-runtab-help
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/enterprisewebservice/agent-office.git
    targetRevision: main
    path: cluster/runtab-help
  destination:
    server: https://kubernetes.default.svc
    namespace: agent-office
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
