apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd-rbac.yaml  # Bootstrap ArgoCD's permission to manage this ns.
  - daemonset.yaml    # Power-cap DS + its Namespace, SA, ConfigMap.
