apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-logging
resources:
  - bucket.yaml
  - bucket-secret-job.yaml
  - lokistack.yaml
  - collector-rbac.yaml
  - clusterlogforwarder.yaml
