apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rbac.yaml
  - sc-card.yaml
  - sc-forge.yaml
  - sc-oracle.yaml
  - sc-report.yaml
  - sc-teardown.yaml
  - supply-chain-e2e.yaml
